### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by jagadish-pattanaik** [piggyvault/piggyvault#272]
```
E/flutter ( 2918): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2601 pos 20: '_debugCurrentBuildTarget == context': is not true.
E/flutter ( 2918): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 2918): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 2918): #2      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2601:20)
E/flutter ( 2918): #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:12)
E/flutter ( 2918): #4      RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
E/flutter ( 2918): #5      WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
E/flutter ( 2918): #6      WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
E/flutter ( 2918): #7      _rootRun (dart:async/zone.dart:1418:47)
E/flutter ( 2918): #8      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 2918): #9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 2918): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 2918): #11     _rootRun (dart:async/zone.dart:1426:13)
E/flutter ( 2918): #12     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 2918): #13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter ( 2918): #14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 2918): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 2918): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 2918): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 2918): 
I/ViewRootImpl@7fc0ae2[MainActivity]( 2918): MSG_WINDOW_FOCUS_CHANGED 0 1

======== Exception caught by widgets library =======================================================
The following StateError was thrown building InheritedProvider<AuthBloc>:
Bad state: Tried to read a provider that threw during the creation of its value.
The exception occurred during the creation of type AuthBloc.

══╡ EXCEPTION CAUGHT BY PROVIDER ╞═══════════════════════════════
The following StateError was thrown:
Bad state: add(AppStarted) was called without a registered event
handler.
Make sure to register a handler via on<AppStarted>((event, emit)
{...})

When the exception was thrown, this was the stack:
#0      Bloc.add.<anonymous closure> (package:bloc/src/bloc.dart:90:9)
#1      Bloc.add (package:bloc/src/bloc.dart:96:6)
#2      main.<anonymous closure> (package:piggy_flutter/main.dart:78:55)
#3      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:736:36)
#4      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:590:33)
#5      _InheritedProviderScopeElement.build (package:provider/src/inherited_provider.dart:544:7)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#10     _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#17     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#24     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#31     _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#38     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#41     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#42     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#43     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#45     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#46     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#47     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
═════════════════════════════════════════════════════════════════

The relevant error-causing widget was: 
  InheritedProvider<AuthBloc> InheritedProvider:file:///C:/Users/acer/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_bloc-8.1.2/lib/src/bloc_provider.dart:126:11
When the exception was thrown, this was the stack: 
#0      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:709:7)
#1      _CreateInheritedProviderState.debugFillProperties (package:provider/src/inherited_provider.dart:806:44)
#2      _InheritedProviderScopeElement.debugFillProperties (package:provider/src/inherited_provider.dart:631:20)
#3      DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2992:17)
#4      DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2995:8)
#5      DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:3009:105)
#6      TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1244:63)
#7      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1121:14)
#8      DiagnosticsNode.toStringDeep.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1776:9)
#9      DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1783:6)
#10     DiagnosticsNode.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1694:18)
#11     DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:1706:6)
#12     Diagnosticable.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3168:78)
#13     Diagnosticable.toString (package:flutter/src/foundation/diagnostics.dart:3170:6)
#14     _StringBase._interpolate (dart:core-patch/string_patch.dart:853:19)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4816:44)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#19     _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411:11)
...     Normal element mounting (7 frames)
#26     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#33     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#40     _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#47     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#50     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#51     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#52     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#53     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#54     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#55     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#56     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building BlocProvider<AuthBloc>:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4531 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  BlocProvider<AuthBloc> BlocProvider:file:///C:/Users/acer/Desktop/Projects/piggy_flutter/lib/main.dart:75:7
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4531:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4534:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#6      SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#13     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#20     _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#27     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#30     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#31     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#32     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#33     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#34     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#35     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#36     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building _NestedHook:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4531 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  _NestedHook _NestedHook:file:///C:/Users/acer/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/nested-1.0.0/lib/nested.dart:103:31
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4531:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4534:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#6      SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#13     _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#20     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#23     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#24     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#25     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#26     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#27     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#28     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#29     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building MultiBlocProvider:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4531 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MultiBlocProvider MultiBlocProvider:file:///C:/Users/acer/Desktop/Projects/piggy_flutter/lib/main.dart:73:17
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4531:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4534:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#6      _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#13     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#16     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#17     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#18     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#20     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#21     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#22     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown attaching to the render tree:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4531 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4531:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4534:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#6      SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1202:16)
#10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1171:5)
#11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1119:18)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1118:13)
#14     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:953:7)
#15     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:933:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

**Comment by jagadish-pattanaik** [comment]
seems like a error at run multiprovider

**Comment by abhith** [comment]
![image](https://user-images.githubusercontent.com/7039457/223447118-31cb984e-0a64-41da-990c-363c0555c92f.png)
![image](https://user-images.githubusercontent.com/7039457/223447172-3f913dcb-6220-4d8b-a0e5-758319212ef0.png)

Working fine on my side with the above setup 🤔

**Comment by abhith** [comment]
Now I did upgrade to the latest flutter version `3.7.6`, and that broke the app due to https://github.com/Ahmadre/FlutterIconPicker/issues/53
Now that is too fixed and things are working fine on my side.
![image](https://user-images.githubusercontent.com/7039457/223457994-cff5b758-6b8f-4ac6-82b6-104781aaaa16.png)

**Comment by jagadish-pattanaik** [comment]
am running on android studio...for mobile app on real device...from main.dart

**Comment by jagadish-pattanaik** [comment]
can you at least figure out where the problem is? so i can give few tries to get it right

**Comment by abhith** [comment]
Can you please cross-check your flutter environment with mine shared above? 
Kindly run the `flutter doctor` and share the result.
Since I can't reproduce the error on my end.

**Comment by jagadish-pattanaik** [comment]
i had upgraded all upgradable dependecies and also changed android sdk version to 33

**Comment by jagadish-pattanaik** [comment]
i will try by lowering the dependecies version to default

**Comment by abhith** [comment]
Oh, I see a major upgrade available for the `flutter_bloc` may be that broke the app.
I didn't tried that upgrade yet.

**Comment by jagadish-pattanaik** [comment]
i think so flutter_block v8 is must be causing some problem..will infrom you shortly

**Comment by jagadish-pattanaik** [comment]
bloc v8 prob... do not upgrade
